#!/usr/bin/env python

Import("env")
Import("env_modules")

env_pxtone = env_modules.Clone()


# env_pxtone.Append(CPPDEFINES=["pxINCLUDE_OGGVORBIS"])

module_obj = []
env_pxtone_lib = env_pxtone.Clone()
env_pxtone_lib.disable_warnings()
env_pxtone_lib.add_source_files(module_obj, "pxtone/*.cpp")

env_pxtone.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

